services:
  # CollabSpace MERN Backend REST API & Socket.io WebSockets Service
  - type: web
    name: collabspace-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    rootDir: server
    envVars:
      - key: PORT
        value: 5001
      - key: MONGO_URI
        sync: false # User provisions this in MongoDB Atlas and pastes the connection string
      - key: JWT_SECRET
        generateValue: true # Securely generates a random secret automatically
      - key: CLOUDINARY_CLOUD_NAME
        sync: false # Cloudinary credentials
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false # Gemini AI api secret key
